site_name: "Xournalpp Pluigin Viewer Docs"
site_url: https://shadowdara.github.io/xournalpp-pluginhub/docs/
use_directory_urls: true

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.top

extra:
  base_url: /docs/
